# Generated by Django 5.1.1 on 2024-10-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='community_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.TextField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('comm_post', models.TextField()),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.TextField(max_length=30)),
                ('topic', models.TextField()),
                ('d_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='debate_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.debate')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.facultyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='stydymaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='studymaterials/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.facultyprofile')),
            ],
        ),
    ]
