# Generated by Django 5.1.1 on 2024-10-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stydymaterials',
            new_name='studymaterials',
        ),
    ]
