# Generated by Django 5.1.1 on 2024-10-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('faculty', '0002_rename_stydymaterials_studymaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='f_studymaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('file', models.FileField(upload_to='studymaterials/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.facultyprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='studymaterials',
        ),
    ]
